Repository ConvergenceSwAce/MJU-Survey-FE, pull requests merged in 2022-11, with the labels that each got.

#2 Feat : 컴포넌트 완성
  public/image/1.gif
  src/App.js
  src/components/Article.js
  src/components/Background.js
  src/components/Header.js
  src/pages/Main.js
Labels: ✅완료

#4 feat : survey 추가
  package-lock.json
  package.json
  src/components/AddressForm.js
  src/components/Result.js
  src/components/SubmitForm.js
  src/pages/Survey.js
Labels: 👨🏻‍💻개발중

#5 Feat : 제출 Form 완성
  src/components/AddressForm.js
  src/components/Result.js
  src/components/SubmitForm.js
  src/pages/Survey.js
Labels: ✅완료, 👀리뷰필요

#8 Feat : result 페이지 디자인
  src/components/paymentForm.js
  src/pages/Result.js
Labels: ✅완료, 👨🏻‍💻개발중

#9 Feat: 1차 백그라운드 디자인 등 수정
  public/image/background.png
  src/App.css
  src/components/Article.js
  src/components/Background.js
  src/components/Header.js
  src/index.css
  src/pages/Main.js
  src/pages/Result.js
  src/pages/Survey.js
Labels: 👀리뷰필요, 👥논의필요, 👨🏻‍💻개발중

#11 chore : 종속성 추가
  src/App.js
  src/components/ProgressBar.js
  src/pages/Result.js
Labels: ✅완료

#12 Feat : 게시판 및 기능 구현
  package-lock.json
  package.json
  src/pages/Result.js
Labels: ✅완료, 👀리뷰필요

#13 Feat : 의견 결과 Stack으로 변경
  src/components/SubmitForm.js
  src/pages/Result.js
Labels: ✅완료

#14 Feat : 종속 셀렉터 완료
  src/components/AddressForm.js
Labels: ✅완료, 👀리뷰필요

#17 Feat : 계단 드롭다운 해결
  src/components/AddressForm.js
  src/pages/Result.js
  src/pages/Survey.js
Labels: ✅완료

#18 Faet : 데이터 차트 추가
  package-lock.json
  package.json
  src/components/Chart.js
  src/pages/Result.js
Labels: ✅완료

#19 Reafactor : axios 수정
  src/pages/Result.js
  src/pages/Survey.js
Labels: ✅완료

#20 Feat : 단과대별 차트 추가
  src/components/Chart.js
  src/pages/Result.js
Labels: 👨🏻‍💻개발중

#21 Chore : dummy 수정
  src/components/Chart.js
Labels: ✅완료

#22 Feat
  .gitignore
  src/components/Chart.js
  src/components/Header.js
  src/pages/Result.js
  src/pages/Survey.js
Labels: ✅완료

#23 Update README.md
  README.md
Labels: ✏️문서
